### ISSUE TITLE
Improve host/target detection for hello_network

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves-examples#17]
The current code uses `:os.type/0`, but this doesn't work if your host is Linux. See https://github.com/nerves-project/nerves_system_br/issues/75 for using `/etc/os-release` or possibly use another mechanism.

**Comment by schnittchen** [comment]
I think any detection mechanism will be flawed. However, `mix` already has the information for us, why not compile it in?

I am thinking about something like this: `Nerves.target` returning

- `:rpi3` if the software was build with `mix firmware` and rpi3 as the configured target
- `nil` if the software was built with vanilla `mix compile` and so will run on the developer's machine, for testing target-independent stuff

I'm making some silent assumptions here about how the mix tasks work internally, which might be totally wrong.

**Comment by GregMefford** [comment]
@fhunleth: I think @schnittchen is talking about having a run-time `Nerves.target` function you can call, that would somehow be injected by `mix` at compile time. I bet that would be possible, but improving what's placed in `/etc/os-release` is also a good idea.

**Comment by schnittchen** [comment]
Checking at runtime is indeed interesting. Being able to do the same check at compile and runtime would be even better, from a usability perspective.

**Comment by mobileoverlord** [comment]
You could set a module attribute to `Mix.Project.config[:target]` to have it available at both compile time and run time.

**Comment by schnittchen** [comment]
If this is helpful to at least a handful people, I'd try to hack this in accessible as `Nerves.target`...

**Comment by fhunleth** [comment]
It's been a year on this issue, and I don't think any PRs have been submitted regarding the comment chain above.

However, we have firmware metadata that's accessible from `Nerves.Runtime.KV` and it includes information about the target that's query-able at runtime and settable in the `mix.exs`. @GregMefford, I think that means this issue can be closed. I'm not sure that the `Nerves.Runtime.KV` feature is well-known yet, so including something in the examples may be useful too.

**Comment by GregMefford** [comment]
I agree that we should close this issue now. If someone finds it here, they'll see the reference to `Nerves.Runtime.KV`. I agree that we should work into an example if it makes sense somewhere, but the reminder to do so isn't worth leaving this issue open.
