### ISSUE TITLE
elixir_ale example

### ISSUE THREAD

**Issue by ulve** [nerves-project/nerves-examples#26]
Is there any interest for an example using [elixir_ale](https://github.com/fhunleth/elixir_ale). If so I would be happy to make a pull request, something simple like controlling a stepper motor perhaps or just a led connected to gpio.

**Comment by fhunleth** [comment]
I think that's a fantastic idea! :smile: Thanks for pinging us about it.

I probably should defer to @ghitchens and @GregMefford who do more of the maintenance of this project, though, before I overstep. Also, I'm not sure which platform that you're working on. I believe that all of us have Raspberry Pis and Beaglebones (Greg - do you have a BBB?), so if it works on one or both of those, then we'll be able to try it out as well. I'd recommend just controlling an LED for simplicity. I'm intrigued that you're driving a stepper motor with elixir_ale, though. I think that's  worth factoring into a small library and posting to hex.pm and the nerves-project.org libraries page.

**Comment by GregMefford** [comment]
That would definitely be great! I'd suggest making a 'stepper' demo and/or
'GPIO' demo rather than an `elixir_ale` example, because people will find
the example based on what they're trying to accomplish, without knowing
that `elixir_ale` is the solution.

**Comment by GregMefford** [comment]
I don't have a BBB, but I have rpi 0, 1, and 2 that I can help test with.

**Comment by ulve** [comment]
Created a minimal project (blinks a led similar to blinky but on gpio using elixir_ale) in pull request #27

Could make a more involved example with both inputs and outputs if anyone is interested or modify this pr to suite the projects needs.

**Comment by GregMefford** [comment]
I think we can go ahead and close this issue since #27 has already been merged. If you want to take some time and submit another PR to add an input example, that would be great as well! Thanks for putting together this example! :rocket:

**Comment by ulve** [comment]
I have done such an example. Will put togheter a PR!

**Comment by ulve** [comment]
Made a pr for this in #28
