### ISSUE TITLE
does not blink on my bbb

### ISSUE THREAD

**Issue by ramstein74** [nerves-project/nerves-examples#4]
Hello i did 
bake system get --target bbb
bake toolchain get --target bbb
bake firmware --target bbb
bake burn --target bbb

the files were created in my sdcard

i put it inside the bbb and boot it.

No blinking leds and no hdmi output...

can you help??

**Comment by fhunleth** [comment]
Our BBB image doesn't use the UART output and not the HDMI output. You'll need a 3.3v I/O FTDI cable (e.g. https://www.sparkfun.com/products/12977 or any similar cable) to see the boot messages and access the iex console. The no blinking LEDs is another problem. That's a little surprising, but I think that I'd need to see what messages get shown on the console to debug that. Barring that, I'd try a clean rebuild.

Fwiw, our Raspberry Pi image does use the HDMI output in case you had one of those around.

**Comment by GregMefford** [comment]
@ramstein74 I just wanted to check in and see whether you've tried again recently with the examples. We have a new workflow that no longer requires Bakeware, but rather integrates directly with Elixir's Mix tool.

It would be great if you could go through the new instructions in the README and let us know if you have any trouble getting it to work!

**Comment by mobileoverlord** [comment]
I think this is a closed issue. I have validated that the bbb is working as expected
