### ISSUE TITLE
Get IP from hello_phoenix

### ISSUE THREAD

**Issue by cdesch** [nerves-project/nerves-examples#47]
How would you get the IP and/or MAC address from the phoenix side of the umbrella application?

**Comment by electricshaman** [comment]
Hi @cdesch, it's the BEAM so normal messaging is available.  For example, you could globally register the name of a GenServer process and then call that from your Phoenix controller or channel, etc.  All the traditional patterns are available.  Here's a similar question posted by someone on StackOverflow: https://stackoverflow.com/a/42642642/139026

**Comment by electricshaman** [comment]
@cdesch I forgot to add that you can retrieve the MAC address and IP from the existing example using the call `Nerves.NetworkInterface.settings "INTERFACE"` (wlan0, eth0, etc.)  Let us know if that answers your question!

**Comment by cdesch** [comment]
@electricshaman Let me give that a try.  Essentially, when the firmware comes online, I want it to self-register with API. Registering the MAC address is a good unique identifier unless there is a different one that is embedded in the system (e.g. Raspberry Pi serial). Alternatively, the firmware could generate a unique hash and store it on the flash storage -- One of the issues I'm trying solve is more around the pairing process of bringing a new node (device) online and the security issues that are involved. For example, using the MAC address is a start, but that doesn't mean that just because the API knows the MAC address, that it should trust that device. I was hoping to have the firmware come online, register with API, receive authorization, store a client-side key for authentication (e.g. JWT). I'm still working out the finer points. Thank you!

**Comment by electricshaman** [comment]
This is a rabbit hole that gets quite deep!  Check into using X.509 certificates provisioned per device.  There is some provisioning overhead and expense, so it may or may not be a feasible solution for your application.  This article explains the concept pretty well, I think:  [Efficient and Secure Provisioning for the IIoT](https://www.digikey.com/en/articles/techzone/2017/mar/efficient-and-secure-provisioning-for-the-iiot)

Good luck!

**Comment by GregMefford** [comment]
I haven't used it myself, but you may also want to look into how the [Amazon IoT](https://aws.amazon.com/iot/) APIs work, for inspiration.

Also, it sounds like you're trying to implement a "kitting" system. You might want to talk with @entone about https://github.com/rosetta-home/kitting_system, which I believe is a work-in-progress to solve a similar problem.

**Comment by GregMefford** [comment]
I'm going to go ahead and close this issue because I think it's not particularly relevant to the examples themselves, but a question about how to provision a Nerves device. If you think the documentation could be improved in this area, please open an issue on either [nerves](https://github.com/nerves-project/nerves) or [nerves_network](https://github.com/nerves-project/nerves_network) as appropriate.

If you just want to discuss how to achieve what you're trying to do, I recommend joining us in the #nerves channel on the [Elixir Slack](https://elixir-slackin.herokuapp.com/), or on [ElixirForum](https://elixirforum.com).

Thanks! 🚀

**Comment by cdesch** [comment]
@GregMefford  @electricshaman  Thanks guys. I'll try something later and post back if I find something.
