### ISSUE TITLE
hello_phoenix compile fails 

### ISSUE THREAD

**Issue by melix2002** [nerves-project/nerves-examples#50]
Hey guys, I've tried to nail down the issue, but I can't really find, where it goes wrong.
Right after 
```
|==================================================| 100% (105 / 105) MB
|Elixir.Nerves.Package.Providers.HTTP| Artifact nerves_system_rpi3-0.11.0.arm_unknown_linux_gnueabihf.tar.gz Downloaded

|Elixir.Nerves.Package.Providers.HTTP| Unpacking nerves_system_rpi3-0.11.0.arm_unknown_linux_gnueabihf.tar.gz
  To Destination:
    /home/melix/projects/tmp/nerves-examples/hello_phoenix/deps/nerves_system_rpi3/.nerves/artifacts/nerves_system_rpi3-0.11.0.arm_unknown_linux_gnueabihf

```
the compiler fails. 
```
** (FunctionClauseError) no function clause matching in Nerves.System.BR.bootstrap/1
    lib/mix/tasks/nerves/loadpaths.ex:16: Mix.Tasks.Nerves.Loadpaths.run/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (nerves) lib/mix/tasks/firmware.ex:21: Mix.Tasks.Firmware.run/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

I've tried already updating packages to: 
```
  def project do
    [app: :fw,
     version: "0.1.0",
     elixir: "~> 1.4.0",
     target: @target,
     archives: [nerves_bootstrap: "~> 0.3.1"],
     deps_path: "../../deps/#{@target}",
     build_path: "../../_build/#{@target}",
     lockfile: "../../mix.lock",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     aliases: aliases(@target),
     deps: deps()]
  end

  def deps do
    [{:nerves, "~> 0.5.2", runtime: false},
    ] ++
    deps(@target)
  end

  # Specify target specific dependencies
  def deps("host"), do: []
  def deps(target) do
    [{:nerves_runtime, "~> 0.1.2"},
     {:"nerves_system_#{target}", "~> 0.12.0", runtime: false},
     {:nerves_networking, "~> 0.6.0"},
     {:nerves_interim_wifi, "~> 0.2.0"},
     {:ui, in_umbrella: true}]
  end
```
with no luck. Maybe you will see the problem directly and can give me an advice, how to fix it.

**Comment by melix2002** [comment]
I have also created a complete new Elixir umbrella app, with nerves and phoenix inside. It fails in the same way while compiling as described above. 
Erlang 19.3
Elixir 1.4.4

**Comment by fpauser** [comment]
Same problem here, full console log under https://gist.github.com/fpauser/b29779fcdc94cd3bcf652d3d9264f43f

**Comment by electricshaman** [comment]
@melix2002 @fpauser Can you try running `mix firmware` inside the `apps/fw` folder?

**Comment by melix2002** [comment]
Under apps/fw it runs flawless, the issue is only if I try to compile it from the root of an umbrella application.

**Comment by electricshaman** [comment]
@melix2002 Yes, that's the expected behavior.  It's a quirk of how we use umbrella applications.  We missed that step in the README for `hello_phoenix`.  Sorry about that!  It's correct here: https://hexdocs.pm/nerves/user-interfaces.html#phoenix-web-interfaces

**Comment by electricshaman** [comment]
Additional information on the umbrella app behavior can be found here too: http://embedded-elixir.com/post/2017-05-19-poncho-projects/

**Comment by melix2002** [comment]
omg...thank you for this advice. I just spent about 8 hours on trial and error and debugging stuff...imho the readme on the first page, is very important. Maybe it should be updated :)

**Comment by electricshaman** [comment]
@melix2002 Done!  You will not have suffered in vain. ;)  https://github.com/nerves-project/nerves-examples/pull/51
