### ISSUE TITLE
Bakefile missing?

### ISSUE THREAD

**Issue by ilkka** [nerves-project/nerves-examples#9]
When following [the Blinky Demo instructions](http://nerves-project.org/learn/blinky-demo/) from nerves-project.org, `bake system get` fails because there is no Bakefile. `bake --version` reports 0.2.8.

**Comment by mobileoverlord** [comment]
Hi @ilkka. We recently integrated the functionality that bake provided directly into `mix`. The new tooling exposes everything using project dependencies and simplifies the whole process. You can learn more about this change by checking out this [announcement video]
(https://www.youtube.com/watch?v=118-g0ODfgg)

And also by checking out our new docs.
https://hexdocs.pm/nerves/getting-started.html

**Comment by ilkka** [comment]
Yeah, thanks, I just found that exact doc through a link on the Slack channel :)
